# Generated by Django 5.1.6 on 2025-03-01 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_filme', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Filme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filme_name', models.CharField(max_length=30)),
                ('filme_year', models.IntegerField()),
            ],
        ),
    ]
